### PR TITLE
Implement Histogram1D if the same measurement is selected for both axes

### LINKED ISSUE #151: Histograms
In case the user chooses the same parameter to plot as X and Y axis, we could draw a histogram instead of a scatter plot. In that case, the lasso tool should just ignore the Y-Axis and allow to select histogram-bins instead.

### PR DESCRIPTION
**Pull request by lazigu**
This PR implements plotting 1D histogram if the same measurement is selected for both axes. Currently, no clustering for this type of histogram is implemented. @zoccoler had an idea that clustering for such a histogram could be done with a span selector (the issue has not been created yet).
Partly closes #151, however, a separate issue regarding clustering 1D histograms should be created.

### CODE REVIEW

**Comment by zoccoler** [comment]
Hi @lazigu , sorry for the delay!
I am implementing the span selector in this PR, so that it becomes complete.

**Comment by zoccoler** [comment]
The histogram still needs to be painted back with the right colors. As metnioned in the commit, somthing like this may work: https://stackoverflow.com/a/49290555/11885372

This is a work in progress.

**Comment by zoccoler** [comment]
Hi @lazigu, hi everyone, the span selection should be working now. The histogram colors now also get updated, having a similar behavior to the other plotting options (histogram 2d and scatter).

I renamed the `HISTOGRAM_2D` to just `HISTOGRAM` now. Whether it is 2D or not comes from the selected measurements.

If both measurements are the same, the histogram is 1D and a span selector is used instead of the lasso. Right-click should reset the clusters.

Could someone test before merging?

Best,
Marcelo

**Comment by haesleinhuepf** [comment]
I love it!

image

**Pull request merged**
