### PR TITLE
Add abstract selector class

### PR DESCRIPTION
**Pull request by jo-mueller**
Hi @zoccoler ,

I started writing something like a basic abstract class for the future selector tool(s). I didn't test whether what you showed recently still works with this implementation but maybe it's a good place to start to make things more standardized and extensible.

Best, Johannes

### CODE REVIEW

**Comment by zoccoler** [comment]
Hi @jo-mueller , I told you in person already, but just for the record here, that is a very good idea and initiative, thanks! I can try to derive on top of that to check what is needed and what is already working. I need some time to test this.

**Comment by zoccoler** [comment]
Hi @jo-mueller ! As we discussed, I am moving the basic plot functionalities to another repo [biaplotter](https://github.com/BiAPoL/biaplotter). Would you mind sending this PR to [this branch there](https://github.com/BiAPoL/biaplotter/tree/artists_and_selectors)?

**Comment by jo-mueller** [comment]
@zoccoler I think I can close this PR as it has been merged elsewhere, right?

**Comment by zoccoler** [comment]
Yes, I intend to bring the biaplotter to the `Restructuring-plotter.py` branch, where there is some work started already

**Pull request closed without merging**
