### PR TITLE
Add perplexity check, fix test

### PR DESCRIPTION
**Pull request by lazigu**
Trying out if pre-commit fails also here

### CODE REVIEW

**Comment by Cryaaa** [comment]
@lazigu, thanks for putting out the fires today first of all. Since we always have problems with code coverage for features which have to be clicked maybe we should remove the checks until we have gotten rid of the measurements widget? Or should we be super strict and make sure every line we right is tested?

**Comment by lazigu** [comment]
Hey Ryan @Cryaaa,

I wasn't worried about the coverage now. There is some kind of different error related to napari-plugins-checks pre-commit hook. Checks pass now because I disabled it for now. Error is weird, I couldn't figure out what was the problem:

Traceback (most recent call last):
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/bin/napari-plugin-check", line 8, in <module>
    sys.exit(main())
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in main
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in <genexpr>
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 131, in check_file
    return function(filename)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 99, in check_py
    return _check_imports(fname)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 112, in _check_imports
    scanner = importscanner.ImportScanner({root: {module}}, fs, True)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/grimp/application/ports/importscanner.py", line 35, in __init__
    for package in self.found_packages:
TypeError: 'FileSystem' object is not iterable
Traceback (most recent call last):
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/bin/napari-plugin-check", line 8, in <module>
    sys.exit(main())
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in main
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 153, in <genexpr>
    return sum(check_file(filename) for filename in args.filenames)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 131, in check_file
    return function(filename)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 99, in check_py
    return _check_imports(fname)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/napari_plugin_checks.py", line 112, in _check_imports
    scanner = importscanner.ImportScanner({root: {module}}, fs, True)
  File "/pc/clone/iswaKIRuSpC2mXd0GYpAUg/py_env-python3/lib/python3.10/site-packages/grimp/application/ports/importscanner.py", line 35, in __init__
    for package in self.found_packages:
TypeError: 'FileSystem' object is not iterable

**Comment by lazigu** [comment]
And this PR doesn't deal with just tests/coverage, I added this perplexity value check (the widget becomes red (screenshot)) to avoid this error when running dim reduction widget because scikit-learn added this [check](https://github.com/scikit-learn/scikit-learn/commit/b54a5289d5090346093ec36dc117ec2a72420563) for algorithm's correctness :)

The error:

_File ~\Miniconda3\envs\ncp-dev\lib\site-packages\sklearn\manifold\_t_sne.py:793, in TSNE._check_params_vs_input(self=TSNE(init='pca', learning_rate='auto', perplexity=30, random_state=42), X=         0         1         2         3        ...289245 -0.557417 -0.597412

[4 rows x 12 columns])
    791 def _check_params_vs_input(self, X):
    792     if self.perplexity >= X.shape[0]:
--> 793         raise ValueError("perplexity must be less than n_samples")

ValueError: perplexity must be less than n_samples_

image

**Review by haesleinhuepf — APPROVED** [review]
Looks good to me @lazigu

Thanks for your time and have a great weekend! 🌞

**Pull request merged**
