### PR TITLE
refactor colormap and put it in the tools menu

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi Ryan @Cryaaa ,

I would like to make the clusters-plotter colormap accessible from the menu so that I can apply it to any label image. I found this solution by refactoring the pre-existing code. I'm just not sure if the `num_labels` parameter of the function `get_nice_color_map_rgba_dict` is really necessary or if it's possible to avoid it. Happy to chat about it in the coming days.

Thanks!
Robert

image

### CODE REVIEW

**Comment by Cryaaa** [comment]
@haesleinhuepf,
I changed the code a bit so that we get rid of the number if labels. This means the colour map is “only” 256 different Color’s but I guess that should be fine? If you agree I’ll merge this 😊

**Comment by haesleinhuepf** [comment]
Hi Ryan @Cryaaa ,

it doesn't work anymore with the new change. The colours are different now.

image

I'm not sure if I understand why though. Your code looks good to me.

**Comment by Cryaaa** [comment]
that is very weird. I had that problem yesterday on my desktop PC but not on my laptop today.... We'll have to investigate before we merge then.....

**Comment by Cryaaa** [comment]
For my own sanity: I have traced down the issue to the length of the colormap it seems that once it reaches about 200 it displays the wrong colors (although the right colors are shown in the little icon). I'll have to investigate what it is exactly but it seems like a bug to me

**Comment by haesleinhuepf** [comment]
Consider talking to the napari developers 😉

**Comment by Cryaaa** [comment]
So this bug seems to appear for several people and it is being investigated by the napari developers currently: https://github.com/napari/napari/issues/4384  Until it's fixed on the napari side I would just stick to the way you implemented it at the beginning @haesleinhuepf .

**Comment by haesleinhuepf** [comment]
See also: https://github.com/napari/napari/issues/4942

**Comment by lazigu** [comment]
@haesleinhuepf, could you tell me if this PR is still relevant? I'm not sure whether I should solve the conflicts and consider merging it or close it due to it being a bit outdated...

**Pull request closed without merging**
