### PR TITLE
added dask arrays support

### LINKED ISSUE #37: `Don't yet support nd fancy indexing` error
Hi all,

Fabrice Senger reported an error [on the image.sc forum](https://forum.image.sc/t/dont-yet-support-nd-fancy-indexing/61878/8): In case the image dataset is loaded as [dask array](https://docs.dask.org/en/stable/array.html), the clusters plotter `Measurement Widget` throws an error (see below).

The solution might be as simple as [this](https://github.com/haesleinhuepf/napari-cupy-image-processing/blob/main/napari_cupy_image_processing/_cupy_image_processing.py#L34):

```
if 'dask.array.core.Array' in str(type(value)):
    value = np.asarray(value)
```

I'm also sure Fabrice would be happy to try out a bug-fix once a new version has been published. :-)

Full error log:
```
NotImplementedError                       Traceback (most recent call last)
~\miniconda3\envs\napari-env\lib\site-packages\napari_clusters_plotter\_measure.py in run_clicked()
    101                 return
    102
--> 103             self.run(
        global self.run = undefined
        global self.image_select.value = undefined
        global self.labels_select.value = undefined
        global self.reg_props_choice_list.value = undefined
        global str = undefined
        global filename_edit.value.absolute.replace.replace = undefined
        global self.closest_points_list.text = undefined
    104                 self.image_select.value,
    105                 self.labels_select.value,

~\miniconda3\envs\napari-env\lib\site-packages\napari_clusters_plotter\_measure.py in run(self=<napari_clusters_plotter._measure.MeasureWidget object>, image_layer=<Image layer 'Image:0'>, labels_layer=<Labels layer 'Image:0 [1]'>, region_props_source='Measure now (with neighborhood data)', reg_props_file='C:/Users/fabrice_senger/  ', n_closest_points_str='2, 3, 4')
    184                 n_closest_points_split = n_closest_points_str.split(",")
    185                 n_closest_points_list = map(int, n_closest_points_split)
--> 186                 reg_props = region_props_with_neighborhood_data(columns, labels_layer.data, n_closest_points_list,
        reg_props = {'label': <class 'numpy.ndarray'> (750,) int32, 'original_label': <class 'numpy.ndarray'> (750,) int32, 'bbox_min_x': <class 'numpy.ndarray'> (750,) float32, 'bbox_min_y': <class 'numpy.ndarray'> (750,) float32, 'bbox_min_z': <class 'numpy.ndarray'> (750,) float32, 'bbox_max_x': <class 'numpy.ndarray'> (750,) float32, 'bbox_max_y': <class 'numpy.ndarray'> (750,) float32, 'bbox_max_z': <class 'numpy.ndarray'> (750,) float32, 'bbox_width': <class 'numpy.ndarray'> (750,) float32, 'bbox_height': <class 'numpy.ndarray'> (750,) float32, 'bbox_depth': <class 'numpy.ndarray'> (750,) float32, 'min_intensity': <class 'numpy.ndarray'> (750,) float32, 'max_intensity': <class 'numpy.ndarray'> (750,) float32, 'sum_intensity': <class 'numpy.ndarray'> (750,) float32, 'area': <class 'numpy.ndarray'> (750,) float32, 'mean_intensity': <class 'numpy.ndarray'> (750,) float32, 'sum_intensity_times_x': <class 'numpy.ndarray'> (750,) float32, 'mass_center_x': <class 'numpy.ndarray'> (750,) float32, 'sum_intensity_times_y': <class 'numpy.ndarray'> (750,) float32, 'mass_center_y': <class 'numpy.ndarray'> (750,) float32, 'sum_intensity_times_z': <class 'numpy.ndarray'> (750,) float32, 'mass_center_z': <class 'numpy.ndarray'> (750,) float32, 'sum_x': <class 'numpy.ndarray'> (750,) float32, 'centroid_x': <class 'numpy.ndarray'> (750,) float32, 'sum_y': <class 'numpy.ndarray'> (750,) float32, 'centroid_y': <class 'numpy.ndarray'> (750,) float32, 'sum_z': <class 'numpy.ndarray'> (750,) float32, 'centroid_z': <class 'numpy.ndarray'> (750,) float32, 'sum_distance_to_centroid': <class 'numpy.ndarray'> (750,) float32, 'mean_distance_to_centroid': <class 'numpy.ndarray'> (750,) float32, 'sum_distance_to_mass_center': <class 'numpy.ndarray'> (750,) float32, 'mean_distance_to_mass_center': <class 'numpy.ndarray'> (750,) float32, 'standard_deviation_intensity': <class 'numpy.ndarray'> (750,) float32, 'max_distance_to_centroid': <class 'numpy.ndarray'> (750,) float32, 'max_distance_to_mass_center': <class 'numpy.ndarray'> (750,) float32, 'mean_max_distance_to_centroid_ratio': <class 'numpy.ndarray'> (750,) float32, 'mean_max_distance_to_mass_center_ratio': <class 'numpy.ndarray'> (750,) float32}
        global region_props_with_neighborhood_data = <function region_props_with_neighborhood_data at 0x0000016DC64CD5E0>
        global columns = undefined
        labels_layer.data = dask.array<astype, shape=(406, 512), dtype=int32, chunksize=(406, 512), chunktype=numpy.ndarray>
        n_closest_points_list = <map object at 0x0000016DB0859CD0>
    187                                                                 reg_props)
    188

~\miniconda3\envs\napari-env\lib\site-packages\napari_clusters_plotter\_measure.py in region_props_with_neighborhood_data(columns=['label', 'centroid_x', 'centroid_y', 'centroid_z'], label_image=dask.array<astype, shape=(406, 512), dtype=int32, chunksize=(406, 512), chunktype=numpy.ndarray>, n_closest_points_list=<map object>, reg_props={'area': <class 'numpy.ndarray'> (750,) float32, 'bbox_depth': <class 'numpy.ndarray'> (750,) float32, 'bbox_height': <class 'numpy.ndarray'> (750,) float32, 'bbox_max_x': <class 'numpy.ndarray'> (750,) float32, 'bbox_max_y': <class 'numpy.ndarray'> (750,) float32, 'bbox_max_z': <class 'numpy.ndarray'> (750,) float32, 'bbox_min_x': <class 'numpy.ndarray'> (750,) float32, 'bbox_min_y': <class 'numpy.ndarray'> (750,) float32, 'bbox_min_z': <class 'numpy.ndarray'> (750,) float32, 'bbox_width': <class 'numpy.ndarray'> (750,) float32, ...})
    200 def region_props_with_neighborhood_data(columns, label_image, n_closest_points_list, reg_props):
    201     # get lowest label index to adjust sizes of measurement arrays
--> 202     min_label = int(np.min(label_image[np.nonzero(label_image)]))
        min_label = undefined
        global int = undefined
        global np.min = <function amin at 0x0000016DFE4CD550>
        label_image = dask.array<astype, shape=(406, 512), dtype=int32, chunksize=(406, 512), chunktype=numpy.ndarray>
        global np.nonzero = <function nonzero at 0x0000016DFE4C8430>
    203
    204     columns = columns + ['min_intensity', 'max_intensity', 'sum_intensity',

~\miniconda3\envs\napari-env\lib\site-packages\dask\array\core.py in __getitem__(self=dask.array<astype, shape=(406, 512), dtype=int32, chunksize=(406, 512), chunktype=numpy.ndarray>, index=(dask.array<getitem, shape=(nan,), dtype=int64, chunksize=(nan,), chunktype=numpy.ndarray>, dask.array<getitem, shape=(nan,), dtype=int64, chunksize=(nan,), chunktype=numpy.ndarray>))
   1837
   1838         if any(isinstance(i, Array) and i.dtype.kind in "iu" for i in index2):
-> 1839             self, index2 = slice_with_int_dask_array(self, index2)
        self = dask.array<astype, shape=(406, 512), dtype=int32, chunksize=(406, 512), chunktype=numpy.ndarray>
        index2 = (dask.array<getitem, shape=(nan,), dtype=int64, chunksize=(nan,), chunktype=numpy.ndarray>, dask.array<getitem, shape=(nan,), dtype=int64, chunksize=(nan,), chunktype=numpy.ndarray>)
        slice_with_int_dask_array = <function slice_with_int_dask_array at 0x0000016DA9DE8DC0>
   1840         if any(isinstance(i, Array) and i.dtype == bool for i in index2):
   1841             self, index2 = slice_with_bool_dask_array(self, index2)

~\miniconda3\envs\napari-env\lib\site-packages\dask\array\slicing.py in slice_with_int_dask_array(x=dask.array<astype, shape=(406, 512), dtype=int32, chunksize=(406, 512), chunktype=numpy.ndarray>, index=(dask.array<getitem, shape=(nan,), dtype=int64, chunksize=(nan,), chunktype=numpy.ndarray>, dask.array<getitem, shape=(nan,), dtype=int64, chunksize=(nan,), chunktype=numpy.ndarray>))
   1020     ]
   1021     if sum(fancy_indexes) > 1:
-> 1022         raise NotImplementedError("Don't yet support nd fancy indexing")
        global NotImplementedError = undefined
   1023
   1024     out_index = []

NotImplementedError: Don't yet support nd fancy indexing
```

### PR DESCRIPTION
**Pull request by zoccoler**
Hi guys,

I have added support for dask arrays that should fix #37 . 
It basically checks if it is a dask_array and converts it to numpy, like Robert suggested.

I added a test to check if it runs without errors now and also fixed the dock_widget tests.
Hopefully all tests will pass now!

Let me know if you find any problems so that we can merge afterwards.

Best,
Marcelo

### CODE REVIEW

**Comment by zoccoler** [comment]
Hmm.. This "pre-commit.ci" is failing. Does someone knows what is this?
I tested locally with `pytest` before.

**Comment by lazigu** [comment]
@zoccoler thanks for this PR, Marcelo! Pre-commit is an autoformatter I added during the weekend:
https://github.com/BiAPoL/napari-clusters-plotter/pull/49

I will fix this when I am back to the pc, it says to comment "pre-commit.ci autofix" on the pull request and it should be all good

**Comment by lazigu** [comment]
pre-commit.ci autofix

**Review by lazigu — APPROVED** [review]
Looks good to me, I will merge it, and after the next release we can have the user that used dask array to test it.

**Pull request merged**
