### PR TITLE
Fix nans in measurements2

### PR DESCRIPTION
**Pull request by jo-mueller**
Closes #65 

Another approach to handling NaNs in the measured properties. I created a decorator for all functions that need to handle data which may potentially be polluted with NaNs.

The decorator assumes that the data is 
* passed as an argument
* the first argument

I think these are reasonable assumptions. The NaNs are then cleared from the data, fed to the decorated function and the original dimensions are restored before returning the data, see [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/760918e2b823f4ef2a25e2ff24e9264f7c20baa6/napari_clusters_plotter/_utilities.py#L45).

Let me know what you think!

### CODE REVIEW

**Comment by Cryaaa** [comment]
Hey @jo-mueller !
I absolutely LOVE this way of handling it, keeps it really nice and tidy and also easy to implement in future! I'll just do some tests on my end and see if this works for me aswell. We might need to take a look at the tests though as there seem to be some issues with failing tests..

**Comment by jo-mueller** [comment]
Hey @Cryaaa ,

thanks!

> there seem to be some issues with failing tests..

PyOpencl error in the github actions...  -_-

**Comment by Cryaaa** [comment]
@jo-mueller ok so I haven't dealt much with these errors up until now... Is it just a bug we have to accept or what can we do to fix this?

**Comment by jo-mueller** [comment]
Let's see if https://github.com/BiAPoL/napari-clusters-plotter/pull/70/commits/4118888e36210ae052f5789c78ffb65fe2e099ae fixes it. I basically replaced the built-in measurement function with the one from skimage and replaced a few values with NaN.

**Comment by jo-mueller** [comment]
Tests failing only for macOS is super-weird.

**Comment by jo-mueller** [comment]
The strangest part is that, according to the error message, an `\n` character appears in arrays that are compared:

```
 assert np.array_equal(result[~np.isnan(result)], 1 - true_class[~np.isnan(result)])
E       assert False
E        +  where False = <function array_equal at 0x10b8765e0>(array([1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0.,\n       1., 1.]), (1 - array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1])))
```

**Comment by Cryaaa** [comment]
@jo-mueller ooooof.. Man This is really annoying to see and (at least for me) I cannot test any mac stuff. Maybe Robert @haesleinhuepf has seen some of these (seemingly) randomly failing test results before and has some hints?

**Comment by jo-mueller** [comment]
Ok now it's even more mysterious as the test fails for Python 3.8 but works for Python 3.9 ^^"

**Comment by lazigu** [comment]
> Ok now it's even more mysterious as the test fails for Python 3.8 but works for Python 3.9 ^^"

Such weird things were happening to me too with some other PR 😅 And sometimes just re-running failed tests helped..

**Pull request merged**
