### PR TITLE
Create CITATION.cff

### LINKED ISSUE #119: Add CITATION.cff file
Hi

Is it possible to add a citation file [CITATION.cff] to the repository?

https://citation-file-format.github.io/

### PR DESCRIPTION
**Pull request by lazigu**
This would close #119 and add such a field to the about section of the repository:
image

Any more info we should add to this file? :)

### CODE REVIEW

**Comment by Cryaaa** [comment]
@lazigu,
This looks good to me! I would add my email but since I’m leaving TU Dresden and will have a new one soon I think I’ll just leave it blank until I have a new address. Thanks for doing this so quickly!

**Review by haesleinhuepf — APPROVED** [review]
Fantastic initiative @lazigu !

**Comment by zoccoler** [comment]
Hey this is super cool @lazigu ! All good for me!

**Review by zoccoler — APPROVED** [review]

**Review by jo-mueller — COMMENTED** [review]
Thumbs up from me 👍

**Pull request merged**
