### PR TITLE
Update axes limits when plotting

### PR DESCRIPTION
**Pull request by thorstenwagner**
I noticed that when switching between layers, the axis limits of the plots are not updated properly. This is due to reset_zoom being called with old axis limits. This PR fixes the problem.

### CODE REVIEW

**Comment by Cryaaa** [comment]
Hey @thorstenwagner,
Is this also a problem for other plotting types like 1D Histograms and scatterplots? If so should we maybe add the line to the other functions too? Apart from that thanks for catching this and the simple fix!

**Comment by thorstenwagner** [comment]
I don't have a good example for the other plotting types. Especially not one with multiple layers

**Comment by thorstenwagner** [comment]
Tried it with a small dataset I've. Seems to work fine for scatter and histogram plots

**Comment by thorstenwagner** [comment]
I can reproduce the issue with scatter plots

**Comment by thorstenwagner** [comment]
Fixed. For histograms I can't reproduce the issue. Seems to work. Ready for merge :-)

**Comment by Cryaaa** [comment]
> Fixed for scatter plots. For histograms I can't reproduce the issue. Seems to work. Ready for merge :-)

Awesome, thanks for checking this and implementing the fix! Everything LGTM

**Pull request merged**
